SELECT name , gender FROM users;
SELECT * FROM users;
SELECT * FROM users WHERE gender <> 'Male';
SELECT * FROM users WHERE date_of_birth < '1995-09-09'; 
SELECT * FROM users WHERE id<=10;
SELECT * FROM users WHERE date_of_birth IS NOT NULL;
SELECT * FROM users WHERE date_of_birth BETWEEN '1990-01-01' AND '1999-12-12';
SELECT * FROM users WHERE gender in ('Male' , 'Female');
SELECT * FROM users WHERE gender='Male' AND salary >= '70000';
SELECT * FROM users WHERE gender='Male' OR salary >= '60000';
SELECT * FROM users WHERE gender='Male' OR salary >= '60000' ORDER BY date_of_birth ASC;
SELECT * FROM users WHERE gender='Male' OR salary >= '60000' ORDER BY date_of_birth DESC;
SELECT * FROM users WHERE gender='Male' OR salary >= '60000' ORDER BY date_of_birth ASC LIMIT 5 ;
SELECT * FROM users WHERE salary > 60000 ORDER BY created_at DESC LIMIT 5;
SELECT * FROM users ORDER BY salary DESC;
SELECT * FROM users WHERE salary BETWEEN 50000 AND 70000;
UPDATE users SET salary = 45000 ,email = 'aarav@aarav.com' WHERE id = 1;
UPDATE users SET salary = 70000 WHERE id = 5;
UPDATE users SET name = 'Aisa Khan' WHERE email = 'aisha@example.com';
UPDATE users SET salary = salary + 10000 WHERE salary < 60000;
SET SQL_SAFE_UPDATES = 0;
